### ISSUE TITLE
App | Google Sign In is not supported in WebView

### ISSUE THREAD

**Issue by Chintan1193** [gdgbaroda/raize#38]
When calling OAuth from app, it redirects to Meetup.com's OAuth. On this screen, if user tries to sign in with Google then it fails. Google's sign in functionality doesn't work in WebView.

**Error: disallowed_useragent**

![Screenshot](https://user-images.githubusercontent.com/13567363/62016458-f51a5100-b1cf-11e9-9612-7f9b8a092308.jpg)

**Comment by mistryhardik** [comment]
@Chintan1193 This issues is caused because the flutter_webview_plugin is actually rendered as a view and not as native webview per platform.

To fix this we specify userAgent parameter when launching the url such as "Chrome/56.0.0".
