### ISSUE TITLE
API Issue | Callback API is not working when calling it individually. 

### ISSUE THREAD

**Issue by Chintan1193** [gdgbaroda/raize#39]
When I call `callback` API individually then it gives **Server Error**.
Please note that when I call `auth` then it returns this url. But to implement in app, I have to call `callback` url as GET API. In this case, it is giving this error.

![SharedScreenshot](https://user-images.githubusercontent.com/13567363/62179459-4fe7b000-b36a-11e9-970a-c1cc21774cea.jpg)

**Comment by mistryhardik** [comment]
@Chintan1193 You can review the changes to the api here: https://raizeapi.azurewebsites.net/api-docs/.

As part of the default callback on route: https://raizeapi.azurewebsites.net/meetup/callback?code=xxxx, you would have to parse the code from the request query parameter.

Then, make another GET request on route https://raizeapi.azurewebsites.net/meetup/callback/token?code=xxx with same query parameter and value from the previous request [NOTE: the use of /token in the route]. This will help you obtain the access token related to the meetup user.

We have tried and tested this approach and does work.

Closing it for now, re-open if there is any other potential issue
